### ISSUE TITLE
Add Jupyter/ipynb notebooks for ease of use

### ISSUE THREAD

**Issue by praveen-palanisamy** [PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook#14]
Requested by @bayareacoder in #13

**Comment by bayareacoder** [comment]
Thanks. Pls make sure to test all scripts in Jupyter notebook. 
For instance this will not work: `os.path.realpath(__file__)` as __file__ is not available there.

**Comment by praveen-palanisamy** [comment]
(Re-posting update here for consolidated reference in one place)
Jupyter/IPython notebooks files for each of the recipes in [Chapter 1](https://github.com/PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook/tree/master/Chapter01) [Chapter 2](https://github.com/PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook/tree/master/Chapter02) and [Chapter 3](https://github.com/PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook/tree/master/Chapter03). The remaining will be added when they are ready and tested.

**Comment by bayareacoder** [comment]
This is great. I was able to run all .ipynb notebooks in Ch1 through Ch3 on Jupyter Notebook running on bare metal Mac OS. Of course I only checked that they ran, not that they actually returned meaningful results (as I noticed some of the iterations were on purpose reduced). Thanks a lot and looking forward to the remaining chapters!

**Comment by bayareacoder** [comment]
Hi @praveen-palanisamy would you have an ETA on when the code from Ch4 onwards would be available as .ipynb?

**Comment by praveen-palanisamy** [comment]
Hi @bayareacoder ,
Thanks for the ask. I have updated the repository to add notebooks for [Chapter04](https://github.com/PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook/tree/master/Chapter04) and [Chapter05](https://github.com/PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook/tree/master/Chapter05).  Hope that helps you at the moment.
