### ISSUE TITLE
comparison to benchmark strategy for the stock & crypto examples

### ISSUE THREAD

**Issue by bayareacoder** [PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook#21]
This is more of a suggestion than an issue, but to gauge the RL performance of the stock and crypto trading examples, it would be useful to compare to a benchmark such as a 'buy & hold' strategy.

**Comment by praveen-palanisamy** [comment]
Good suggestion.
If you happen to be trying out such a strategy, it will be great to have your pull request for the example.
