### ISSUE TITLE
Why use env.slip instead of self.slip_probability

### ISSUE THREAD

**Issue by QuantHao** [PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook#23]
Hi, @praveen-palanisamy 

It seems that you try to calcualted weight average of returns at
https://github.com/PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook/blob/61175498f62a4e7f9e9a0906d8da587681e3c11b/Chapter02/2_value_based_rl.py#L41-L42

If my understand is correct, then why not use self.slip_probability when recording
https://github.com/PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook/blob/61175498f62a4e7f9e9a0906d8da587681e3c11b/Chapter02/2_value_based_rl.py#L37
and 
https://github.com/PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook/blob/61175498f62a4e7f9e9a0906d8da587681e3c11b/Chapter02/2_value_based_rl.py#L40

It would make more sense to use self.slip_probability above. Please correct me if I am wrong.

**Comment by praveen-palanisamy** [comment]
Hi @QuantHao ,

You are right! It should be `slip_probability` (not `slip`) which is the transition probability used in the value estimation. 
Thank you for reporting this. I have fixed the typo in a PR and will be merged soon.
