### ISSUE TITLE
Move reverse outside for loop?

### ISSUE THREAD

**Issue by QuantHao** [PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook#27]
Hi, @praveen-palanisamy 

When compute discounted rewards, it seems that reverse should be moved outsdie of for loop.
https://github.com/PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook/blob/101f9866f6105b0ac696f9881d475b8a525eb8ea/Chapter02/7_policy_gradients.py#L58-L61

**Comment by praveen-palanisamy** [comment]
Hey @QuantHao ,
Thanks for spotting and reporting this bug! You are right, the `reverse()` on the `discounted_rewards` should be done outside the for loop. I'll fix the extra indent and update it soon.
