### ISSUE TITLE
Why reward is scaled by 0.01?

### ISSUE THREAD

**Issue by QuantHao** [PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook#31]
Hi, @praveen-palanisamy 

May I ask what's the reason to scale reward down by 0.01?
https://github.com/PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook/blob/997f7e3bf1ca65baa21c9d44e5c5d64c4f685b20/Chapter03/1_double_dqn.py#L124-L126

while still accumulate episode reward as original scale?
https://github.com/PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook/blob/997f7e3bf1ca65baa21c9d44e5c5d64c4f685b20/Chapter03/1_double_dqn.py#L127

**Comment by praveen-palanisamy** [comment]
There's no particular reason for this reward scaling. It was just a heuristic for a particular RL environment which I must have forgotten to remove. 
Thanks for bringing this to my notice. I'll remove the `* 0.01` to avoid confusion.
