### ISSUE TITLE
divide by 8 in A3C?

### ISSUE THREAD

**Issue by QuantHao** [PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook#33]
Hi, @praveen-palanisamy 

May I ask why we need to divided by 8 in A3C agent? https://github.com/PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook/blob/997f7e3bf1ca65baa21c9d44e5c5d64c4f685b20/Chapter03/5_a3c_continuous.py#L213-L215

**Comment by praveen-palanisamy** [comment]
Not necessary! This is just like #31, a environment-specific heuristic that crept in and I forgot to clean it up. Such scaling factors sometimes help with some environments but they are mostly not useful. I'll remove this along with the other items in a PR and merge soon.
