### ISSUE TITLE
Is rewards missing in TD target?

### ISSUE THREAD

**Issue by QuantHao** [PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook#34]
Hi, @praveen-palanisamy 

It seems that _targets[i]_ should be _rewards[i]+args.gamma*q_values[i]_ instead of https://github.com/PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook/blob/997f7e3bf1ca65baa21c9d44e5c5d64c4f685b20/Chapter03/7_ddpg.py#L176

Could you please help me verify?

**Comment by praveen-palanisamy** [comment]
Yes, that sounds right for the TD target. The `reward[i]` is missing and is a bug.
Thanks (multiple times now :)) for reporting this.
