### ISSUE TITLE
sac_agent_base

### ISSUE THREAD

**Issue by chokosabe** [PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook#9]
There is an sac_agent_base.py file in the Chapter08 folder but there isn't one in the. Chapter07 folder though its being called locally in the Chapter07 module. Is this intentional?

**Comment by praveen-palanisamy** [comment]
Hi @chokosabe !
Thank you for pointing this out. Like you mentioned, the [`sac_agent_base` module](https://github.com/PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook/blob/master/Chapter07/sac_agent_runtime.py) is indeed used in [Chapter 7](https://github.com/PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook/tree/master/Chapter07) in the [3rd Recipe on Training RL Agents Using Remote Sims](https://github.com/PacktPublishing/Tensorflow-2-Reinforcement-Learning-Cookbook/blob/master/Chapter07/3_training_rl_agents_using_remote_sims.py). So, I have added the module in #10.
